services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_toko
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - simple-php-app
  www:
    depends_on:
      - db
    image: php:apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
    networks:
      - simple-php-app
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - simple-php-app
networks:
  simple-php-app:
    driver: bridge
